// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFF61UezzLZKirJMIVbRoVDtCdu_wOfK4',
    appId: '1:695410741005:web:0387c26a0ac598cf0daa44',
    messagingSenderId: '695410741005',
    projectId: 'w_app-bibha',
    authDomain: 'w_app-bibha.firebaseapp.com',
    storageBucket: 'w_app-bibha.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrNmM7OZIQ-DoGZSf18E4V-IiX02BkQTQ',
    appId: '1:695410741005:android:7cd65d6c397782990daa44',
    messagingSenderId: '695410741005',
    projectId: 'w_app-bibha',
    storageBucket: 'w_app-bibha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG1Uk0HMY5e7Kyx_2iNjY4SsxNBCfao84',
    appId: '1:695410741005:ios:aee36261854c5e0c0daa44',
    messagingSenderId: '695410741005',
    projectId: 'w_app-bibha',
    storageBucket: 'w_app-bibha.firebasestorage.app',
    iosBundleId: 'com.example.w_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG1Uk0HMY5e7Kyx_2iNjY4SsxNBCfao84',
    appId: '1:695410741005:ios:aee36261854c5e0c0daa44',
    messagingSenderId: '695410741005',
    projectId: 'w_app-bibha',
    storageBucket: 'w_app-bibha.firebasestorage.app',
    iosBundleId: 'com.example.w_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFF61UezzLZKirJMIVbRoVDtCdu_wOfK4',
    appId: '1:695410741005:web:b85c13c31a19c2f60daa44',
    messagingSenderId: '695410741005',
    projectId: 'w_app-bibha',
    authDomain: 'w_app-bibha.firebaseapp.com',
    storageBucket: 'w_app-bibha.firebasestorage.app',
  );
}
